version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # ports:
      # - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: test
      PMA_PASSWORD: test
    networks:
      - app-network

  backend:
    build:
      context: ./server
    container_name: backend
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: mydatabase
    ports:
      - "3001:3001"
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3001
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
